version: "3"
services:
  customers-service:
    image: espay/customers-service-api
    container_name: customers-service
    build:
      context: ./customers-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      OTEL_SERVICE_NAME: customers
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACE_EXPORTER: jaeger
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    depends_on:
      mysql:
        condition: service_healthy
      axon:
        condition: service_healthy
      jaeger:
        condition: service_started
    networks:
      - internal
  payments-service:
    image: espay/payments-service-api
    container_name: payments-service
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      OTEL_SERVICE_NAME: payments
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACE_EXPORTER: jaeger
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    depends_on:
      mysql:
        condition: service_healthy
      axon:
        condition: service_healthy
      jaeger:
        condition: service_started
    networks:
      - internal

  axon:
    image: axoniq/axonserver
    container_name: axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    depends_on:
      - jaeger
    networks:
      - internal
    healthcheck:
      test: curl -f http://axon:8024/actuator/health
      interval: 5s
      retries: 100

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: axonserver
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - internal
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "4317:4317"
      - "4318:4318"
    networks:
      - internal
networks:
  internal:
    driver: bridge
