version: '3'
services:
  axon:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    depends_on:
      - jaeger
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: axonserver
    ports:
      - "3306:3306"
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
