version: '3'
services:
  axon:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: axonserver
    ports:
      - "3306:3306"