server:
  port: 8762
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: espay-adquirer
          uri: lb://ESPAY-ADQUIRER
          predicates:
            - Path=/adquirers/**
        - id: espay-card-network
          uri: lb://ESPAY-CARD-NETWORK
          predicates:
            - Path=/card-networks/**
        - id: espay-customers
          uri: lb://ESPAY-CUSTOMERS
          predicates:
            - Path=/customers/**
        - id: espay-payments
          uri: lb://ESPAY-PAYMENTS
          predicates:
            - Path=/payments/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}