server:
  port: 8762
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: card-network-service
          uri: lb://ESPAY-PAYMENTS
          predicates:
            - Path=/payments/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}